using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace EldritchGames.EldritchLogger.EditorTools.CodeGen
{
    /// <summary>
    /// Generates a static class with one <c>LogCategory</c> field per configured category,
    /// so category names are checked by the compiler instead of typed as strings.
    /// </summary>
    public static class CategoryCodeGenerator
    {
        /// <summary>Returns the source code for the category class.</summary>
        /// <param name="categoryNames">Category names, in the order they should appear.</param>
        /// <param name="namespaceName">Namespace, or empty for the global namespace.</param>
        /// <param name="className">Name of the generated static class.</param>
        public static string Generate(IEnumerable<string> categoryNames, string namespaceName, string className)
        {
            if (categoryNames == null) throw new ArgumentNullException(nameof(categoryNames));
            className = ToIdentifier(string.IsNullOrWhiteSpace(className) ? "LogCategories" : className);
            bool hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
            string indent = hasNamespace ? "    " : string.Empty;

            var fields = new List<(string field, string name)>();
            var usedFields = new HashSet<string>(StringComparer.Ordinal) { "All" };
            foreach (var raw in categoryNames)
            {
                if (string.IsNullOrWhiteSpace(raw)) continue;
                var name = raw.Trim();
                if (fields.Any(f => string.Equals(f.name, name, StringComparison.OrdinalIgnoreCase))) continue;

                var field = ToIdentifier(name);
                var unique = field;
                for (int i = 2; !usedFields.Add(unique); i++) unique = field + i;
                fields.Add((unique, name));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Eldritch Logger from the LogSettings categories. Do not edit by hand:");
            sb.AppendLine("// regenerate from Edit > Project Settings > Eldritch Logger.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using EldritchGames.EldritchLogger.Core;");
            sb.AppendLine();

            if (hasNamespace)
            {
                sb.Append("namespace ").AppendLine(namespaceName.Trim());
                sb.AppendLine("{");
            }

            sb.Append(indent).Append("public static class ").AppendLine(className);
            sb.Append(indent).AppendLine("{");
            foreach (var (field, name) in fields)
            {
                sb.Append(indent).Append("    public static readonly LogCategory ").Append(field)
                  .Append(" = new LogCategory(\"").Append(Escape(name)).AppendLine("\");");
            }

            if (fields.Count > 0) sb.AppendLine();
            sb.Append(indent).Append("    public static readonly LogCategory[] All = { ")
              .Append(string.Join(", ", fields.Select(f => f.field)))
              .AppendLine(fields.Count > 0 ? " };" : "};");
            sb.Append(indent).AppendLine("}");

            if (hasNamespace) sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Converts a category name such as <c>"loot drops"</c> into <c>LootDrops</c>.</summary>
        public static string ToIdentifier(string name)
        {
            var sb = new StringBuilder();
            bool upperNext = true;
            foreach (var c in name ?? string.Empty)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(upperNext ? char.ToUpper(c, CultureInfo.InvariantCulture) : c);
                    upperNext = false;
                }
                else
                {
                    upperNext = true;
                }
            }

            if (sb.Length == 0) sb.Append("Category");
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');

            // PascalCasing means the result can never be a (lowercase) C# keyword.
            return sb.ToString();
        }

        private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
